### ISSUE TITLE
Compiling fail in Manjaro linux 

### ISSUE THREAD

**Issue by limbail** [RapidsOfficial/Rapids#36]
Linux 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux

## Compiling fail with:
configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)

## Compiling with option "--with-incompatible-bdb" fail with:
  CXX      rapidsd-pivxd.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blocksignature.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      consensus/libbitcoin_server_a-params.o
  CXX      consensus/libbitcoin_server_a-tx_verify.o
  CXX      consensus/libbitcoin_server_a-zerocoin_verify.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:73:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   73 |     std::deque<WorkItem*> queue;
      |          ^~~~~
httpserver.cpp:31:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   30 | #include <event2/keyvalq_struct.h>
  +++ |+#include <deque>
   31 | 
httpserver.cpp: In destructor ‘WorkQueue<WorkItem>::~WorkQueue()’:
httpserver.cpp:107:17: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  107 |         while (!queue.empty()) {
      |                 ^~~~~
      |                 Enqueue
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:116:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  116 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:119:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  119 |         queue.push_back(item);
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:131:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  131 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:135:21: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  135 |                 i = queue.front();
      |                     ^~~~~
      |                     Enqueue
httpserver.cpp: In member function ‘size_t WorkQueue<WorkItem>::Depth()’:
httpserver.cpp:161:16: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  161 |         return queue.size();
      |                ^~~~~
      |                Enqueue

**Comment by volbil** [comment]
Fixed by https://github.com/RapidsOfficial/Rapids/pull/37

**Comment by limbail** [comment]
## Still fail:

asd@Rapids-4.0]$ make
Making all in src
make[1]: Entering directory '/home/asd/Downloads/Rapids-4.0/src'
make[2]: Entering directory '/home/asd/Downloads/Rapids-4.0/src'
  CXX      rapidsd-pivxd.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blocksignature.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      consensus/libbitcoin_server_a-params.o
  CXX      consensus/libbitcoin_server_a-tx_verify.o
  CXX      consensus/libbitcoin_server_a-zerocoin_verify.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:73:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   73 |     std::deque<WorkItem*> queue;
      |          ^~~~~
httpserver.cpp:31:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   30 | #include <event2/keyvalq_struct.h>
  +++ |+#include <deque>
   31 | 
httpserver.cpp: In destructor ‘WorkQueue<WorkItem>::~WorkQueue()’:
httpserver.cpp:107:17: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  107 |         while (!queue.empty()) {
      |                 ^~~~~
      |                 Enqueue
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:116:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  116 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:119:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  119 |         queue.push_back(item);
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:131:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  131 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:135:21: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  135 |                 i = queue.front();
      |                     ^~~~~
      |                     Enqueue
httpserver.cpp: In member function ‘size_t WorkQueue<WorkItem>::Depth()’:
httpserver.cpp:161:16: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  161 |         return queue.size();
      |                ^~~~~
      |                Enqueue
make[2]: *** [Makefile:7625: libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory '/home/asd/Downloads/Rapids-4.0/src'
make[1]: *** [Makefile:12978: all-recursive] Error 1
make[1]: Leaving directory '/home/asd/Downloads/Rapids-4.0/src'
make: *** [Makefile:780: all-recursive] Error 1
